# Generated by Django 4.1.2 on 2022-10-18 20:22

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumptionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Goodsid', models.CharField(max_length=20)),
                ('Storeid', models.CharField(max_length=20)),
                ('Guest', models.CharField(max_length=20)),
                ('Quantity', models.IntegerField()),
                ('Time', models.DateField()),
                ('Goodsprice', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Consumption',
                'managed': True,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Goodsid', models.CharField(max_length=20)),
                ('Storeid', models.CharField(max_length=20)),
                ('Goodstitle', models.CharField(max_length=100)),
                ('Goodsprice', models.FloatField()),
                ('Goodssailed', models.IntegerField()),
                ('Goodsrevenue', models.DecimalField(decimal_places=3, max_digits=11)),
            ],
            options={
                'db_table': 'Goods',
                'managed': True,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GoodsStoreHistoricalMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Goodsid', models.CharField(max_length=20)),
                ('Storeid', models.CharField(max_length=20)),
                ('Goodstitle', models.CharField(max_length=100)),
                ('Goodssailed', models.IntegerField()),
                ('Goodsrevenue', models.DecimalField(decimal_places=3, max_digits=11)),
                ('Time', models.DateField()),
            ],
            options={
                'db_table': 'GoodsStoreHistoricalMonth',
                'managed': True,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StoreHistoricalMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Storeid', models.CharField(max_length=20)),
                ('Storetitle', models.CharField(max_length=100)),
                ('Storesailed', models.IntegerField()),
                ('Sturerevenue', models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True)),
                ('Time', models.DateField()),
            ],
            options={
                'db_table': 'StoreHistoricalMonth',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StoreInfo',
            fields=[
                ('Storeid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Storetitle', models.CharField(max_length=100)),
                ('Storeaddress', models.CharField(max_length=100)),
                ('Storesailed', models.IntegerField()),
                ('Sturerevenue', models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True)),
            ],
            options={
                'db_table': 'Store',
                'managed': True,
            },
        ),
    ]
