# Generated by Django 4.1.2 on 2022-10-18 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_initial'),
    ]

    operations = [
    ]
